###GET

GET http://localhost:4004/odata/v4/purchase-order/PurchaseOrderHeader

###GET

GET http://localhost:4004/odata/v4/purchase-order/$metadata


###POST
POST http://localhost:4004/odata/v4/purchase-order/PurchaseOrderHeader
Content-Type: application/json
Accept: application/json

{
      "PurchaseOrder": "PO00000018",
      "CompanyCode": "1000",
      "PurchaseOrderType_OrderType": "NB",
      "PurchasingOrganization": "1000",
      "PurchaseGroup": "001",
      "Supplier_ID": "11111111-1111-1111-1111-111111111111",
      "Language_code": "EN",
      "OrderDate": "2025-09-01",
      "DocumentCurrency_code": "USD",
      "OverallStatus_code": "P"
}


###DELETE


###PATCH